//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlxWebsiteFyp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feed
    {
        public int f_id { get; set; }
        [Display(Name="Name")]
        public string f_name { get; set; }

        [Display(Name = "Description")]
        public string f_description { get; set; }

        [Display(Name = "Link")]
        public string f_link { get; set; }
    }
}
