//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlxWebsiteFyp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int i_id { get; set; }
        public Nullable<int> re_id { get; set; }

        [Display(Name ="Name")]
        public string i_name { get; set; }
        [Display(Name = "Price")]
        public string i_price { get; set; }

        [Display(Name = "Image")]
        public string i_image { get; set; }

        [Display(Name = "Seller Status")]
        public Nullable<int> i_status { get; set; }

        [Display(Name = "Contact")]
        public string i_contact { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public string i_date { get; set; }

        [Display(Name = "Category")]
        public Nullable<int> c_id { get; set; }

        [Display(Name = "Admin Status")]
        public Nullable<int> i_active { get; set; }

        [Display(Name = "Rent Days")]
        public string rent_days { get; set; }

        [Display(Name = "Link To Share")]
        public string link_contact { get; set; }

        [Display(Name = "Price Per")]
        public string days_of_price { get; set; }

     
        public virtual Category Category { get; set; }
    }
}
